### ISSUE TITLE
can't use ember-cli and nvm?

### ISSUE THREAD

**Issue by donahchoo** [Turbo87/intellij-emberjs#16] opened 2015-12-11 03:52 UTC
Hi,

I have ember-cli installed via nvm @ ~/.nvm/versions/node/v0.12.7/bin/ember

If I try to create a new file I get this error:

Problem running ember-cli: Cannot run program "ember" (in directory "/Users/me/Developer/ember/ember-note"): error=2, No such file or directory

echo $PATH includes /Users/me/.nvm/versions/node/v0.12.7/bin

also, does the new Ember.js command support pods?

**Comment by panthony** [comment] 2015-12-11 06:35
Hi @donahchoo

Maybe you ran into the same problem as me with #8 ?

I had to start intellij from the command line to make it work.

For now, if you want to create pods components using this plugin you'll have to create a file ".ember-cli" with
```json
{
  "usePods": true
}
```
It will make ember-cli use --pods option by default for all generate commands. See http://ember-cli.com/extending/#pods for more infos.

**Comment by Turbo87** [comment] 2015-12-11 07:57
duplicate of #8

**Closed by Turbo87** 2015-12-11 07:57 UTC
