### ISSUE TITLE
Running `ember serve` in IntelliJ from Run (^R) throws error - exiting with code 127

### ISSUE THREAD

**Issue by rinoldsimon** [Turbo87/intellij-emberjs#239] opened 2018-10-22 03:09 UTC
### Description

/Users/workspace/web_ui/node_modules/.bin/ember serve
env: node: No such file or directory

Process finished with exit code 127

### Steps to Reproduce

- at times, after newly opening IntelliJ IDE
- when i restart the IDE it works fine

**Expected behavior:** Start ember server

**Actual behavior:** Throws error in `Run` tool window

**Reproduces how often:** Alternate number of times.

### Versions

- IntelliJ:

IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018

- The version of `intellij-emberjs`:

2018.2.4-0

**Comment by Turbo87** [comment] 2018-10-22 12:21
duplicate of #238

**Closed by Turbo87** 2018-10-22 12:21 UTC
